### ISSUE TITLE
Get banned every week

### ISSUE THREAD

**Issue by crydante** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#104]
I live in France and every week i am banned. If i reboot my modem, with a new IP it works again.

My config is : 

language: en-US
polling_schedule: "*/20 * * * *"
intense_fetch_interval: 30
intense_fetch_period_of_time: 5

In the log i have this error : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 303, in fetch_loop
    if not check():
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 46, in check
    shops = tgtg_client.get_items(page_size=400)
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 256, in get_items
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd=

What can i try to do not be banned again

**Comment by Dielee** [comment]
Let the api cool down over night. My cron looks like this and I never get banned: 

`"polling_schedule": "*/2 8-19 * * *",
 "intense_fetch": {"interval": 30, "period_of_time": 1}`

**Comment by crydante** [comment]
Thank you i will try this

**Comment by crydante** [comment]
Get banned again : 

polling_schedule: "*/10 7-20 * * *"
intense_fetch_interval: 30
intense_fetch_period_of_time: 1

**Comment by Dielee** [comment]
Are you running multiple tgtg bridges ?

**Comment by crydante** [comment]
No, i run only once on my home assistant on a raspberry pi

**Comment by crydante** [comment]
All my settings :

![2022-11-14_11h38_03](https://user-images.githubusercontent.com/21313422/201639267-b18bfd43-646d-4efc-8279-02e8e3e3e8c4.png)

Maybe language parameter are important to not be banned

**Comment by Dielee** [comment]
Yes, please try this

**Comment by JoRosk** [comment]
Any update on this?
I got the same error.

**Comment by fsa317** [comment]
Can someone better explain how the intense fetch works?

**Comment by MaxWinterstein** [comment]
> Any update on this? I got the same error.

It's still some kind of ~magic~ blackbox how these rate limiter works. As far as I can tell, I get banned too, when running multiple instances at the same time. 

---



> Can someone better explain how the intense fetch works?

What is your question in detail? 

There are some words written here: https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge#tgtgintense_fetch-optional
