### ISSUE TITLE
No tokens found, check email adres for login. No email received.

### ISSUE THREAD

**Issue by Florian14490** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#125]
Hi,

After I used this addon perfectly for a while the tokens are not found anymore.
Since a few days I see that the addon is not working anymore. (i think after updating to new HA februari, not sure)

Addon error: Token not found, check mail box for login.
Oke, that sounds formiliar. But no mails are getting in my mail box.

Re installed addon with same config. Same problem.

Installed the [Chouffy](https://github.com/Chouffy)
 TGTG stock sensor from HACS
After complete python scripts. I got the login email in mailbox and gets after few more steps the TGTG stock sensors updated.

So thats working. But why I cant get your addon working anymore? Someting changed what I did not see?

Hope there is a answer, all automations were working through your tgtg-mqtt addon :) Want to get it working again.

Already thanks.
Greetz Florian

**Comment by MaxWinterstein** [comment]
Can you share the Add-On logs please?

**Comment by Florian14490** [comment]
@MaxWinterstein 
Yes, sure:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 2.5.1.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.2
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh
[16:30:58] INFO: Copy settings file
No saved tokens found.
Please make sure to check your email for the login request and answer quickly.
You can't open it on a mobile phone where the TGTG app itself is installed.
cont-init: info: /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun toogoodtogo-ha-mqtt-bridge (no readiness notification)
s6-rc: info: service legacy-services successfully started
[16:30:58] INFO: Strating Bridge...
2023-02-07 16:31:03 [INFO] Connecting mqtt
2023-02-07 16:31:03 [INFO] Starting loop
2023-02-07 16:31:03 [INFO] Logging in with credentials
Exception in thread Thread-3 (fetch_loop):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 324, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 168, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAHTqWCSOQdEwAUc4AQg==&cid=1P7rgxWK_u3zIK6u~u-oXss~6sOVoJrPCpa934HGMlZCRnaF1ABgn1ZMmPyHKt_M_Hm8BN078FWJANDBS5y7Cv2B8rj9uIUTcYWnTEb68bTbdCs2_V01jtcBcluMfdfE&referer=https%3A%2F%2Fapptoogoodtogo.com%2Fapi%2Fauth%2Fv3%2FauthByEmail&hash=1D42C2CA6131C526E09F294FE96F94&t=fe&s=35587&e=e87205eef905a88d05dc64744a92cc8a9a808448dffe6834d8b565f94684ee0a"}')

**Comment by MaxWinterstein** [comment]
Well, I am not sure what's happening there. It smells like the commonly known 'Datadome captcha' issue, where data dome, the service that protects the tgtg api, things somebody tries to abuse it.

Does this still happen? can you connect new your internet to get a new IP address?

**Comment by Florian14490** [comment]
I will test your addon via my test Home assistant @ work. Its total different ip adres.

But strange thing is, via hacs integration (chouffy) and pyhton script tgtg_get_tokens. I got de login mail from tgtg and everything works.
Thats only weird thing I noticed.

**Comment by Florian14490** [comment]
Yes , your addon is working on my test setup. Got the login mail in no time.

I think my home ip adres is blocked by tgtg,...

**Comment by MaxWinterstein** [comment]
I guess, yeah. Still an issue that happens and no one found a good workaround for...
