### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by poudenes** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#145]
Hi All,

Suddenly TgTg didn't updated anymore in HA. See those errors now:

```
2023-05-30 17:20:48 [INFO] Connecting mqtt
Traceback (most recent call last):
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 636, in <module>
    start()
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 615, in start
    mqtt_client.connect(host=settings.mqtt.host, port=int(settings.mqtt.port))
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
```

Tried to restart docker. Didn't work

**Comment by poudenes** [comment]
after some checks there was something with my MQTT problem solved

**Comment by MaxWinterstein** [comment]
Happy to see you figured it out 👍
