### ISSUE TITLE
Exception during starting

### ISSUE THREAD

**Issue by FeikoJoosten** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#15]
Just noticed an email spam from TGTG regarding a new login. Checked the log and saw the following:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.6  (amd64 / qemux86-64)
 Home Assistant Core: 2021.10.6
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:06:01] INFO: Copy setings file
[15:06:01] INFO: Strating Bridge
2021-11-02 15:06:01 1e14b3fb-tgtg-ha-mqtt-bridge __main__[310] INFO Connecting mqtt
2021-11-02 15:06:01 1e14b3fb-tgtg-ha-mqtt-bridge __main__[310] INFO Starting loop
2021-11-02 15:06:01 1e14b3fb-tgtg-ha-mqtt-bridge __main__[310] DEBUG Loop run started
2021-11-02 15:06:02 1e14b3fb-tgtg-ha-mqtt-bridge __main__[310] DEBUG Pushing message for Lidl - de Lier (Groente & Fruitbox) // 327522
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "toogoodtogo_ha_mqtt_bridge/main.py", line 149, in loop
    if not check():
  File "toogoodtogo_ha_mqtt_bridge/main.py", line 62, in check
    price = shop["item"]["price"]["minor_units"] / pow(10, shop["item"]["price"]["decimals"])
KeyError: 'price'
```

**Comment by HumanPrinter** [comment]
I see the same thing happening. Running the following setup:
Core: core-2021.10.7
SuperVisor: supervisor-2021.10.8
OS: Home Assistant OS 6.6
Add-on: 1.7.0

**Comment by FeikoJoosten** [comment]
Ty, I forgot to mention my version numbers. Running the exact same setup, apart from my core still being on 2021.10.6

**Comment by liudger** [comment]
it happens here too. I think it's an api change. Didn't update my system recently

**Comment by poudenes** [comment]
Same issue. Nothing changed on system side.

**Comment by MaxWinterstein** [comment]
Thanks for the issue and info @all <3

Seems like they really changed their API at this point.  
As I am low on time for this one I added some quick fix that should do the job. 

New versions:  
**bridge itself:** `v1.7.0`
**addon** `1.8.0` 

Please leave feedback if it works for you.

**Comment by HumanPrinter** [comment]
Works on my machine :) 

Looks like a decent changeset, thanks for the quick action

**Comment by DavyRoswinkel** [comment]
Problem solved! Thanks again
