### ISSUE TITLE
Bridge won't start anymore

### ISSUE THREAD

**Issue by remyderuysscher** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#154]
I reinstalled the add-on with previous configuration. I noticed that it stopped working a few weeks ago. 

Running HA 2024.1.6

`[08:46:26] INFO: Strating Bridge...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 636, in <module>
    start()
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 603, in start
    email=settings.tgtg.email, language=settings.tgtg.language, timeout=30, user_agent=build_ua()
                                                                                       ^^^^^^^^^^
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 171, in build_ua
    app_info = app("com.app.tgtg", lang="de", country="de")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_play_scraper/features/app.py", line 15, in app
    dom = get(url)
          ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_play_scraper/utils/request.py", line 28, in get
    return _urlopen(url)
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_play_scraper/utils/request.py", line 11, in _urlopen
    resp = urlopen(obj)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
if: fatal: unable to spawn s6-test: No such file or directory`

**Comment by XxCabbyoO** [comment]
Same Error for me 😢

**Comment by MaxWinterstein** [comment]
@remyderuysscher  / @XxCabbyoO  can you provide me some more info? More output? 

@remyderuysscher  HA 2024.1.6? Thats preeeetty old in HA world ;)

For me - running amd64 - it works fine 🤔
