### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by gr8er1mark** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#219]
Hi All

I am having an issue with TGTG login. Previously I would receive the TGTG email and open the link on a device without the app and everything works as expected. However since installing the last update this no longer seems to work. Clicking the TGTG link opens the web browser and show the standard message that sign is has been successful but then I continue to get the emails asking me to login.

When I check the add ons log it shows the below error which makes it looks like a captcha is stopping the add on login.

TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/

Appreciate any help you might be able to offer.

Thanks

**Comment by liudger** [comment]
turn of the add-on. (wait 30 min to be sure) reboot and you should receive an email when you have boot on start up enabled for the add-on.

**Comment by LJ-Stevo** [comment]
Still having trouble keeping it up and running...
In this log I started fresh at 23/12/24 at 18:00 by waiting more then a day to be unblocked again. (somewhere in the middel of the txt file)
Fresh installed, so I get the mail to log in again. Then it works... for 4 hours... Again Captcha... Suddenly it works again?? Without doing anything? But then back again Captcha. Have fun reading my log :-)
I hope you can find a fix for this, because I loved it realy much!
[f1c878cb_tgtg-ha-mqtt-bridge_2024-12-24T19-45-47.607Z.log](https://github.com/user-attachments/files/18241746/f1c878cb_tgtg-ha-mqtt-bridge_2024-12-24T19-45-47.607Z.log)

**Comment by LJ-Stevo** [comment]
> Still having trouble keeping it up and running... In this log I started fresh at 23/12/24 at 18:00 by waiting more then a day to be unblocked again. (somewhere in the middel of the txt file) Fresh installed, so I get the mail to log in again. Then it works... for 4 hours... Again Captcha... Suddenly it works again?? Without doing anything? But then back again Captcha. Have fun reading my log :-) I hope you can find a fix for this, because I loved it realy much! [f1c878cb_tgtg-ha-mqtt-bridge_2024-12-24T19-45-47.607Z.log](https://github.com/user-attachments/files/18241746/f1c878cb_tgtg-ha-mqtt-bridge_2024-12-24T19-45-47.607Z.log)

Little update: If I check regularly the app itself, from time to time I first get a screen that checks something like the captcha but I can't remember what it says. I'm gonna try to take a screenshot next time.
But since then, the error is gone. if the captcha error returns, I just have to go to the app and that check screen appears again, and all is good for a while.
But there must be a solution for this, because that can't be forever like this... Now I always keep an eye on it, but that is not the intention of this add-on ofcourse! ;-)
So please help me (or us) out.

**Comment by LJ-Stevo** [comment]
> If the captcha error returns, I just have to go to the app and that check screen appears again, and all is good for a while.

When I'm at home, I can't do that outside without having my home IP adress!

**Comment by HanBarn** [comment]
I got the 403 error too.
It looks like TGTG has changed something (again..) so the IP is blocked faster than before.
My configuration is already changed. The polling is now every 15 minutes during the daytime (08:00-20:00).
This means a not frequent polling interval.
This should be no problem but I am getting the 403 error too and the Captcha.
Stopping the Add-on for some time is a temporary fix.
I don’t think it is related to the Add-on but more related to TGTG itself.
The TGTG app however does not have any issues and is running fine.
(using the same IP, Wifi network)

**Comment by MaxWinterstein** [comment]
I removed some code that stored a cookie by datadome, if I remember it correctly. I thought this was already handled within the upstream library, or superfluous at least. 

I will have a second look at this, it might be an good explanation for it. Maybe I wrote something about that cookie in my traffic analysis with _mitm proxy_ I did back then. 

Fingers crossed I find some time these days 🤞

**Comment by MaxWinterstein** [comment]
It seems like the datadome cookie thing was in fact merged in the upstream tgtg repo (seems like I was involved in it, too 😄  https://github.com/ahivert/tgtg-python/commit/ee19450b6114c04dce6b626fa00d5ffedd53217e )

It seems like datadome, the company used by tgtg to prevent bad guys doing bad things on their API, got more restrictive I guess.

There are multiple related issues out there:
* https://github.com/ahivert/tgtg-python/issues/321
* https://github.com/Chouffy/home_assistant_tgtg/issues/129
* and some more


I had some little play with the API, and ended in the well known 

```
tgtg.exceptions.TgtgAPIError: (429, 'Too many requests. Try again later.')
```

Which also blocked the whole Android APP on my phone as well.

---

I might need to wait a little bit to get unblocked again, or nuke half my network to get a new IP, and have a fresh look at the traffic between the app and and API. 

Tricky situation.

**Comment by LJ-Stevo** [comment]
A lot is just Chinese for me, but I have faith in you! :-)

**Comment by Shusaku1** [comment]
Hi everyone,

I'm new here and trying to catch up with the current situation regarding the TGTG API and login challenges.

So far, I’ve attempted the following steps:

Tried using the API directly, but it wouldn’t allow me to log in, redirecting me to a CAPTCHA page instead.
To bypass this, I set up an emulator running a rooted Android device with Magisk. This allowed me to install a Mitmproxy CA certificate, enabling me to monitor HTTP/HTTPS traffic but not for TGTG. The app detects something is wrong and I can't do any action.
My goal was to intercept the authentication tokens needed for logging in, but it seems that just installing the Mitmproxy CA certificate isn’t sufficient (maybe there is certificate pinning.)

I wanted to ask:
Have you encountered similar issues with certificate pinning while working with the API or monitoring TGTG traffic?
Is Mitmproxy a step you also went through, or were you able to use the API without these additional steps?
I’d appreciate any advice! If there’s a workaround or a preferred method
Thanks!

**Comment by wenzet** [comment]
Before finding this repository I implemented something similar with the same python package. Overall the implementation was more or less the same - just way simpler.
 
Back then I had similar issues when fetching too many shops too fast. So I added a delay between each `get_item()` call.  
It was a bit of trial and error but 15 seconds appeared to work more or less.  
@MaxWinterstein Maybe it's worth to have a look into #226. It's more like a draft but maybe that could work - at least as some type of workaround.

**Comment by HanBarn** [comment]
> Before finding this repository I implemented something similar with the same python package. Overall the implementation was more or less the same - just way simpler.
> 
> Back then I had similar issues when fetching too many shops too fast. So I added a delay between each `get_item()` call. It was a bit of trial and error but 15 seconds appeared to work more or less. [@MaxWinterstein](https://github.com/MaxWinterstein) Maybe it's worth to have a look into [#226](https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/pull/226). It's more like a draft but maybe that could work - at least as some type of workaround.

Is there any progress on this issue?
Is it possible to add a time delay manually somewhere as a workaround?
TGTG is still temporary blocking me even if the polling interval is 5 minutes or more.
May be less favorite shops is an option too to limit the amount of requests.

**Comment by LJ-Stevo** [comment]
The only way I can keep it "working" is to open the app on the phone when I'm home, so then I have the same IP address.
When I get the captcha error in the log of tgtg add-on, I just go to the app and I instant get a verifying screen. When thats done, the next polling is working again for a few hours. But the point is ofcourse, checking the app all the time is just that we want to avoid by using this add-on. So I'm also hoping there will be a work around for this...

**Comment by HanBarn** [comment]
> The only way I can keep it "working" is to open the app on the phone when I'm home, so then I have the same IP address. When I get the captcha error in the log of tgtg add-on, I just go to the app and I instant get a verifying screen. When thats done, the next polling is working again for a few hours. But the point is ofcourse, checking the app all the time is just that we want to avoid by using this add-on. So I'm also hoping there will be a work around for this...
> 
> Edit: Is this something that can help? https://habr.com/en/articles/865274/

I have never seen something in the TGTG app on my iPhone when the captcha message is showing in the log.
The app on my iPhone is working fine and I can refresh the info as much as needed.
Of course HA and my iPhone are on the same network at home.

**Comment by LJ-Stevo** [comment]
![Image](https://github.com/user-attachments/assets/51ae6b65-d28b-4fbd-a5d2-d98e2a5aeb0c)

**Comment by LJ-Stevo** [comment]
@HanBarn 
The app on my iPhone is working fine and I can refresh the info as much as needed.

I was refreshing in my favorite list so much because I'm waiting for one to come up and suddenly I get a screen to check if I'm human. So refreshing a lot in the app does that too for me. And I mean a lot, like for 5 min non stop...

**Comment by HanBarn** [comment]
> [@HanBarn](https://github.com/HanBarn) The app on my iPhone is working fine and I can refresh the info as much as needed.
> 
> I was refreshing in my favorite list so much because I'm waiting for one to come up and suddenly I get a screen to check if I'm human. So refreshing a lot in the app does that too for me. And I mean a lot, like for 5 min non stop...

Allright, that makes sense if you use the TGTG a lot to check if there will be a box available for you.
Fact is that the app does allow quite a lot of requests.
Far more than we now see using the integration. 
I hope there will be a solution soon so we can use the integration again as before.

**Comment by LJ-Stevo** [comment]
New problem I think...

I restarted and this is what I get:

[404.txt](https://github.com/user-attachments/files/19013012/404.txt)

**Comment by HanBarn** [comment]
> New problem I think...
> 
> I restarted and this is what I get:
> 
> [404.txt](https://github.com/user-attachments/files/19013012/404.txt)


Yes.
There are more issues related to this.
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/258

**Comment by MaxWinterstein** [comment]
> It looks like there is a fix in the TGTG API client. Max, can you please checks this? [@MaxWinterstein](https://github.com/MaxWinterstein)
> 
> See this: [ahivert/tgtg-python#336](https://github.com/ahivert/tgtg-python/pull/336)

will have a deeper look later on, but at first peek it seems not to fix the login flow stuff, just the refresh endpoint for existing ones

**Comment by MaxWinterstein** [comment]
I just found a few minutes for this project, and I am somehow confused: **it works?**

![Image](https://github.com/user-attachments/assets/669aafcf-f97f-44c3-a750-211fd4be896d)

Can someone verify this for me? Is it still broken for everyone?

**Comment by wenzet** [comment]
@MaxWinterstein 
It does - but after some time it stops working. Got it working today after reinstalling and just had a look couple of minutes ago: It stopped after almost exactly 4 hrs. Then 404 again.

**Comment by MaxWinterstein** [comment]
@wenzet this should be fixed with the release I just did a few moments ago (just here, TGTG Addon needs to be released, hope to get this done today)

The main dependency `tgtg` was updated to `0.18.2` which had some fixes regarding the refresh endpoint, see https://github.com/ahivert/tgtg-python/pull/336

Those 4 hours are hardcoded here:

https://github.com/ahivert/tgtg-python/blob/3fb879a87c9034b6a0dd94339bf85c087ed2560c/tgtg/__init__.py#L33

**Comment by MaxWinterstein** [comment]
The god of bad scripts was with me and the release is ready  🥳 

Updating worked flawless for me, did not need to uninstall before:

![Image](https://github.com/user-attachments/assets/cd8b415b-0682-4ed3-9314-08251b4ca9d5)

Still confused what happened, and why the weird issues are gone, but I take it.

**Comment by MaxWinterstein** [comment]
Still issues out there? 

Otherwise closing this 🥳

**Comment by josvink66** [comment]
Stable for me for me for the last 24 hours after updating! Great job @MaxWinterstein

**Comment by LJ-Stevo** [comment]
I also can confirm it's working like a charm! thank you very much @MaxWinterstein ! <3

**Comment by HanBarn** [comment]
It’s stable here too since yesterday.
Thanks again.

**Comment by hobbypunk90** [comment]
@MaxWinterstein stable for a few days, but for me it's back again 😢

**Comment by LJ-Stevo** [comment]
Yes, same here. After the reboot from update of HA OS 15.0
https://github.com/home-assistant/operating-system/releases/tag/15.0

Now I get this:

2025-03-19 18:15:29 [ERROR] Watchdog handler fired! No pull in the last 14.95 minutes!
NoneType: None
if: fatal: unable to spawn s6-test: No such file or directory
[18:15:30] INFO: [32mStrating Bridge...[0m
2025-03-19 18:15:31 [INFO] Connecting mqtt
Traceback (most recent call last):
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 619, in <module>
    start()
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 597, in start
    mqtt_client.connect(host=settings.mqtt.host, port=int(settings.mqtt.port))
  File "/app/.venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 1435, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 1598, in reconnect
    self._sock = self._create_socket()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 4609, in _create_socket
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/paho/mqtt/client.py", line 4640, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by Qpernicus** [comment]
No problem here. Am on the latest HA and OS (so 15).

**Comment by Qpernicus** [comment]
> No problem here. Am on the latest HA and OS (so 15). 

The issue is back. It worked like a charm for a while but now it's broke again. Noticed it after a reboot but not sure if that's the cause.

**Comment by HanBarn** [comment]
> > No problem here. Am on the latest HA and OS (so 15).
> 
> The issue is back. It worked like a charm for a while but now it's broke again. Noticed it after a reboot but not sure if that's the cause.

Same here. 😢
I does not look like a reboot has something to do with it.
It work good for some time but probably TGTG changed something (again!).

**Comment by Qpernicus** [comment]
> > > No problem here. Am on the latest HA and OS (so 15).
> > 
> > The issue is back. It worked like a charm for a while but now it's broke again. Noticed it after a reboot but not sure if that's the cause.
> 
> Same here. 😢
> I does not look like a reboot has something to do with it.
> It work good for some time but probably TGTG changed something (again!).
> 

Yeah. And all of a sudden it started working again for now. So seems a little intermittent

**Comment by Nailik** [comment]
same issue for me unfortunately `tgtg.exceptions.TgtgAPIError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?`

**Comment by wimpie007** [comment]
This seems to be a semi-working solution for the 403 since this week: (also for me)
https://github.com/Der-Henning/tgtg/issues/590#issuecomment-2831043201

**Comment by MaxWinterstein** [comment]
> This seems to be a semi-working solution for the 403 since this week: (also for me) [Der-Henning/tgtg#590 (comment)](https://github.com/Der-Henning/tgtg/issues/590#issuecomment-2831043201)

Mhm, interesting approach

https://github.com/Der-Henning/tgtg/pull/592

**Comment by wimpie007** [comment]
it has been working for many hours with the 'fix'.
With the lateste official tgtg-client, it wouldnt even get items for 1 time. (immediately after mail-login, error 403)

**Comment by MaxWinterstein** [comment]
Will have a look, thanks for the hint 👍

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MaxWinterstein** [comment]
I quickly and dirty added the `x-correlation-id` header and pushed out a new version. 

Please test if this improves stuff ✌

**Comment by hobbypunk90** [comment]
@MaxWinterstein updated, all data deleted, 403, no login possible 🥲

**Comment by HanBarn** [comment]
> I quickly and dirty added the `x-correlation-id` header and pushed out a new version.
> 
> Please test if this improves stuff ✌

Upgraded about two hours ago.
Integration is running fine now.
Polling interval on my side is 5 minutes.
Will monitor this for a while.

Thanks again for your help!

**Comment by swellbr** [comment]
Updated. Cool down for some hours. Start.
Worked with a 9 minute schedule for about 8 hours, but since then: TgtgAPIError 403

**Comment by HanBarn** [comment]
Running fine here for more than two days.
Polling schedule daily at a 5 minutes interval between 08:00-20:00.
During the night no polling is needed here.
Will monitor the integration.
No HA reboot yet since some days.

**Comment by MaxWinterstein** [comment]
I am happy to see this seems wo work - at least a little bit.

The magic behind their 'protection' is still a mystery, but it seems after a cooldown/ip change and being gentle to the API, it should work.

**Comment by Nailik** [comment]
Newest version seems to be working for me as well (10 min interval between 8 and 21 pm), without a new ip.
Now running for 10 hrs without problems.

**Comment by HanBarn** [comment]
Updated to the latest release 3.3.0.0
I have noticed that the time or time zone has changed somewhere.
My polling schedule is set between 08:00-20:00 but the integration is running until 20:55 (21:00)
One hour later.
The configuration has not been changed. 
Time setting:
Europe/Amsterdam

**Comment by mantaalex** [comment]
the person who fixes this 403 can have an donation of me to ;)

**Comment by LJ-Stevo** [comment]
@mantaalex  I can try to help you? You can add me on discord "ljstevo" for faster communication. ;-) Because you speak dutch I think?

**Comment by mantaalex** [comment]
@MaxWinterstein i don't know if it could help here but https://github.com/ahivert/tgtg-python
is updated to 0.18.4
since i still have the login errors (always error 403)
and i'm using the same config that works for @LJ-Stevo

**Comment by MaxWinterstein** [comment]
> [@MaxWinterstein](https://github.com/MaxWinterstein) i don't know if it could help here but https://github.com/ahivert/tgtg-python is updated to 0.18.4 since i still have the login errors (always error 403) and i'm using the same config that works for [@LJ-Stevo](https://github.com/LJ-Stevo) maybe it fixes something?

Update is prepared, see #253 

Will try to test later ✌️

**Comment by HanBarn** [comment]
No issues here.
Running stable now for weeks.

polling_schedule: "*/5 8-20 * * *"
  intense_fetch_interval: 10
  intense_fetch_period_of_time: 5

**Comment by mantaalex** [comment]
it works after the new release:

<img width="795" height="296" alt="Image" src="https://github.com/user-attachments/assets/f98434b5-cb1f-4180-93f2-45a3c3b74ceb" />
thanks for this fix !!

**Comment by LJ-Stevo** [comment]
@MaxWinterstein , can I poke you here? Are you aware of the new problem? Can you please take a look? Or give us a sign of life will ya ;-)
