### ISSUE TITLE
tgtg.exceptions.TgtgLoginError  403 error

### ISSUE THREAD

**Issue by liudger** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#50]
```
[17:42:14] INFO: Strating Bridge...
2022-06-16 17:42:18 [INFO] Connecting mqtt
2022-06-16 17:42:18 [INFO] Starting loop
2022-06-16 17:42:18 [DEBUG] Logging in with credentials
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 206, in loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 150, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMASflhHtJpFAAAUki2Bg==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35587,\'e\':\'88813e964a961aaf224aacd76ad10cd17bac64f9df470e6256663ab4a9f70657\',\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')
```

Loading without a token (fresh install) gives the same error. I think we need an update

**Comment by Dielee** [comment]
Have a look at #49. The fix is done, we only need to rebase tomorrow. Maybe @MaxWinterstein will merge tomorrow.

**Comment by MaxWinterstein** [comment]
Will try to do all the work later this day

**Comment by Dielee** [comment]
Fix is released. Please test!

**Comment by poudenes** [comment]
I now receive every minute or so a email with a auth token. I can't add the somewhere ...

**Comment by MaxWinterstein** [comment]
@poudenes did you restart it another time? 

Issue is known at #55

**Comment by poudenes** [comment]
It seems to work now ... sorry for dub issue.
