### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno -3] Try again

### ISSUE THREAD

**Issue by DavyRoswinkel** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#57]
Multiple errors in logfile. But restarting or waiting and then the addon continues, normally.
This errors only happens after hours( 10-12 hour) of running the addon. Or does it happen unnoticed??? ( I can't really tell) 
I am using a 2 minute polling_schedule.
Using the newest version v2.2.3
This kind of error also was noticed by me with version 2.2.1 ( version 2.2.2 was to short in use to notice)
  
```
2022-06-19 19:30:38 [DEBUG] Loop run started
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/local/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 283, in loop
    if not is_latest_version():
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 159, in is_latest_version
    app_info = app("com.app.tgtg", lang="de", country="de")
  File "/usr/local/lib/python3.8/site-packages/google_play_scraper/features/app.py", line 15, in app
    dom = get(url)
  File "/usr/local/lib/python3.8/site-packages/google_play_scraper/utils/request.py", line 28, in get
    return _urlopen(url)
  File "/usr/local/lib/python3.8/site-packages/google_play_scraper/utils/request.py", line 11, in _urlopen
    resp = urlopen(obj)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Try again

```

**Comment by HanBarn** [comment]
Just updated from 2.2.2 to 2.2.3 this evening.
No issues.


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 2.2.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2022.5.5
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: executing... 
[21:41:29] INFO: Copy setings file
Saved tokens found.
If you encoure problems reinstalling the add-on might help.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:41:29] INFO: Strating Bridge...
2022-06-19 21:41:30 [INFO] Connecting mqtt
2022-06-19 21:41:30 [INFO] Starting loop
2022-06-19 21:41:30 [INFO] Loaded tokens form tokenfile. Logging in with tokens.
2022-06-19 21:41:30 [INFO] Next run at 2022-06-19 21:57:20
2022-06-19 21:57:20 [DEBUG] Loop run started
2022-06-19 21:57:21 [DEBUG] Pushing message for ….
<cut some messages> 
2022-06-19 21:57:21 [DEBUG] known_shops.json exists at /data//known_shops.json
2022-06-19 21:57:21 [DEBUG] Loop run finished
2022-06-19 21:57:21 [INFO] Next run at 2022-06-19 22:02:37

**Comment by DavyRoswinkel** [comment]
@HanBarn I only have an issue after many hours (10-12) And after waiting or restarting it works normal again

**Comment by HanBarn** [comment]
> @HanBarn I only have an issue after many hours (10-12) And after waiting or restarting it works normal again

Ok, clear.
I have to wait a little bit longer then for the results.

**Comment by Dielee** [comment]
This seems to be an problem with your internet connection, or something ist blocking the playstore scraping part.
I will move this feature in an own thread, so this wont happen anymore. But please be patient, I'm working on an intense mode feature.

**Comment by DavyRoswinkel** [comment]
> This seems to be an problem with your internet connection, or something ist blocking the playstore scraping part. I will move this feature in an own thread, so this wont happen anymore. But please be patient, I'm working on an intense mode feature.

I will double check my Pihole, probably that's the cause.

**Comment by MaxWinterstein** [comment]
Don’t know about your providers in NL, but here in the land of the hard working people with no humor aka Germany a common product is DSL. This is regularly reconnected though the provider, afair around every 24h. 

A good starting point in issues like this is to ensure a stable connection is available.

I do this by using two simple sensors:
```yaml
binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: Ping google by IP
    scan_interval: 5
  - platform: ping
    host: www.google.de
    name: Ping google by DNS
    scan_interval: 5
``

**Comment by DavyRoswinkel** [comment]
Here in the Netherlands ( I live in the countryside) I have a 1000/1000 Mbit/s connection. ( 3 years ago it was only 2mbps) 
Line is stable. Will make the binary sensors and look into it.
The error I mentioned above hasn't showed up anymore.

That being said...let's close this issue...as it isn't an issue...

Take care!
