### ISSUE TITLE
Disconnects every 10-30 minutes

### ISSUE THREAD

**Issue by DavyRoswinkel** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#8]
The bridge disconnects every 10-30 minutes. The log of the toogoodtogo-ha-mqtt-bridge:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f922b5310>: Failed to establish a new connection: [Errno -3] Try again
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apptoogoodtogo.com', port=443): Max retries exceeded with url: /api/item/v7/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f922b5310>: Failed to establish a new connection: [Errno -3] Try again'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "toogoodtogo_ha_mqtt_bridge/main.py", line 148, in loop
    if not check():
  File "toogoodtogo_ha_mqtt_bridge/main.py", line 32, in check
    shops = tgtg_client.get_items(page_size=400)
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 163, in get_items
    response = requests.post(
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='apptoogoodtogo.com', port=443): Max retries exceeded with url: /api/item/v7/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f922b5310>: Failed to establish a new connection: [Errno -3] Try again'))
2021-03-31 16:29:39 f1c878cb-tgtg-ha-mqtt-bridge __main__[307] ERROR Wow, mqtt client lost connection. Will try to reconnect once in 30s.
2021-03-31 16:30:09 f1c878cb-tgtg-ha-mqtt-bridge __main__[307] DEBUG Trying to reconnect

After this the bridge reconnects ( watchdog)
And everything works again for 10 - 30 minutes
Supervisor log:
WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with f1c878cb_tgtg-ha-mqtt-bridge!

Mosquitto broker log:
1617201118: Socket error on client toogoodtogo-ha-mqtt-bridge, disconnecting.
1617201141: New connection from 172.30.32.1 on port 1883.
1617201141: New client connected from 172.30.32.1 as toogoodtogo-ha-mqtt-bridge (p2, c1, k60, u'***')

If more info is needed please let me know

Can you help me?

**Comment by DavyRoswinkel** [comment]
Looks like it's related to #https://github.com/home-assistant/addons/issues/1887  ( looks solved by deinstalling and reinstalling the broker)

**Comment by DavyRoswinkel** [comment]
The error stil occurs. Every 10-30 minutes. People are talking about problems with the broker version. My knowledge doesn't go that far to see if this error is caused by the broker or something different.

So, still need help in finding a solution.
