### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by Aspyryan** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#9]
I was succesfully able to connect to the mqtt server, but when it tries to login to my tgtg account, it gives this error, ive tried restarting the networking service, but I think they might have moved domains? idk, look forward to seeing some help :)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 78, in loop
    if not check():
  File "main.py", line 29, in check
    shops = tgtg_client.get_items(page_size=400)
  File "/usr/local/lib/python3.7/site-packages/tgtg/__init__.py", line 142, in get_items
    self._login()
  File "/usr/local/lib/python3.7/site-packages/tgtg/__init__.py", line 112, in _login
    timeout=self.timeout,
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='apptoogoodtogo.com', port=443): Max retries exceeded with url: /api/auth/v1/loginByEmail (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb5ad7050>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by MaxWinterstein** [comment]
Is this still a thing? 

(sorry, never saw a notification for this issue)
