### ISSUE TITLE
Can't update to version 2.4

### ISSUE THREAD

**Issue by DarKOrange75** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#90]
Hi, I can't update to the latest version, I run HA 2022.7.7 on HA OS thank you for your help.

2022-08-20 18:34:41 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547857501920] Error updating TooGoodToGo Home Assistant MQTT Bridge: Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64&platform=linux%2Farm64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0 not found: manifest unknown: manifest unknown")
homeassistant.components.hassio.handler.HassioAPIError: Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64&platform=linux%2Farm64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0 not found: manifest unknown: manifest unknown")
homeassistant.exceptions.HomeAssistantError: Error updating TooGoodToGo Home Assistant MQTT Bridge: Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64&platform=linux%2Farm64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0 not found: manifest unknown: manifest unknown")

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 18:33:46 (8 occurrences) 
Last logged: 18:49:02

[547857501920] Error updating TooGoodToGo Home Assistant MQTT Bridge: Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64&platform=linux%2Farm64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0 not found: manifest unknown: manifest unknown")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 45, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64&platform=linux%2Farm64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0 not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 152, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 411, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating TooGoodToGo Home Assistant MQTT Bridge: Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64&platform=linux%2Farm64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-aarch64:2.4.0 not found: manifest unknown: manifest unknown")

**Comment by gr8er1mark** [comment]
I am receiving the same error message when trying to update.

**Comment by HanBarn** [comment]
See this:
https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/issues/87

**Comment by MaxWinterstein** [comment]
Update should now be available. Pls try again :)

GitHub action (aka. Build pipeline) was broken. Need to overhaul this process in total, one day, when I win the time lottery and can work on all my stuff……

**Comment by DarKOrange75** [comment]
It worked :-) thank you so much for your time and great work, this add-on is awesome and very useful to me! cheers
